"""
Contains all constant string literals for effect names, etc.
This helps avoid typos and makes it easier to manage these values.
"""

# --- Effect Name Constants ---
EFFECT_NAME_BROKEN_BLADE_DEBUFF = "BROKEN_BLADE_DEBUFF"
EFFECT_NAME_FIRST_STRIKE_RAGE_AURA = "FIRST_STRIKE_RAGE_AURA"
EFFECT_NAME_AWAKENING_DMG_REDUCTION = "Awakening Damage Reduction"
EFFECT_NAME_PENDING_AWAKENING_CLEANSE = "PENDING_AWAKENING_CLEANSE"
EFFECT_NAME_PENDING_LOKIS_TRICK_BUFF_REMOVAL = "PENDING_LOKIS_TRICK_BUFF_REMOVAL"
EFFECT_NAME_PENDING_SHIELD_REFLECTOR_REMOVAL = "PENDING_SHIELD_REFLECTOR_REMOVAL"
EFFECT_NAME_DISARM_DEBUFF = "Disarm Debuff"
EFFECT_NAME_SLOW_DEBUFF = "Slow Debuff"
EFFECT_NAME_SILENCE_DEBUFF = "Silence Debuff"


EFFECT_NAME_BLADE_COUNTER_BOOST = "Blade Counter Boost"
EFFECT_NAME_BLADE_COUNTER_IMMUNITY = "Broken Blade Immunity"
EFFECT_NAME_SHIELD_OF_RESISTANCE = "Shield of Resistance Effect"
EFFECT_NAME_REVENGE_ECHO_COUNTER_BOOST = "Revenge Echo Counter Boost"
EFFECT_NAME_BLIZZARD_SPEAR_SHIELD = "Blizzard Spear Shield"
EFFECT_NAME_HOLY_SHIELD_BOOST = "Holy Shield Boost"
EFFECT_NAME_DIVINE_RESISTANCE_BASIC_DMG_RED = "Divine Resistance (Basic Dmg Reduction)"
EFFECT_NAME_DIVINE_RESISTANCE_COUNTER_BOOST = "Divine Resistance (Counter Dmg Boost)"
EFFECT_NAME_HEALING_CHORDS_BOOST = "Healing Chords Boost"
EFFECT_NAME_HOLD_FAST_SHIELD = "Hold Fast Shield"
EFFECT_NAME_DETERMINED_DEFENSE_BROKEN_BLADE = EFFECT_NAME_BROKEN_BLADE_DEBUFF
EFFECT_NAME_TIT_FOR_TAT_DMG_RED = "Tit for Tat Damage Reduction"
EFFECT_NAME_SHARP_PURSUIT_SHIELD = "Sharp Pursuit Shield"
EFFECT_NAME_FLAME_GUARDIAN_SHIELD = "Flame Guardian Shield"
EFFECT_NAME_SACRED_BLADE_ATTACK_BOOST = "Sacred Blade Attack Boost"
EFFECT_NAME_SANCTITY_H2_RAGE_BOOST = "Sanctity of Life (H2 Rage Dmg Boost)"
EFFECT_NAME_VITAL_BLESSING_COUNTER_BOOST = "Vital Blessing Counter Boost"
EFFECT_NAME_VANQUISHING_BLADE_REDUCTION = "Vanquishing Blade Reduction"
EFFECT_NAME_FORCEFUL_AMBUSH_COUNTER_BOOST = "Forceful Ambush Counter Boost"
EFFECT_NAME_FORCEFUL_AMBUSH_SHIELD = "Forceful Ambush Shield"
EFFECT_NAME_DIVINE_BLESSING_REDUCTION = "Divine Blessing Reduction"
EFFECT_NAME_SHIELD_SUPPORT_EFFECT = "Shield Support Effect"
EFFECT_NAME_FREYAS_BLESSING_HEAL_BOOST = "Freya's Blessing Heal Boost"
EFFECT_NAME_HYMN_OF_LIFE_HOT = "Hymn of Life (HoT)"
EFFECT_NAME_HYMN_OF_LIFE_HP_BOOST = "Hymn of Life HP Boost"
EFFECT_NAME_SHIELD_REFLECTOR_BUFF = "Shield Reflector Buff"
EFFECT_NAME_BALDRS_SHIELD = "Baldr's Shield"
EFFECT_NAME_BALDRS_RESILIENCE = "Baldr's Resilience"
EFFECT_NAME_BALDRS_HEAL = "Baldr's Heal"
EFFECT_NAME_ODINS_ASYLUM_SHIELD = "Odin's Asylum Shield"
EFFECT_NAME_THORS_DETERMINATION_BUFF = "Thor's Determination Buff"
EFFECT_NAME_THORS_DETERMINATION_DMG_REDUCTION = "Thor's Determination Damage Reduction"
EFFECT_NAME_DISARMAMENT_DISARM = EFFECT_NAME_DISARM_DEBUFF
EFFECT_NAME_DISARMAMENT_SLOW = EFFECT_NAME_SLOW_DEBUFF

EFFECT_NAME_FIERY_SNAKE_SPIRIT_H1_BOOST = "Fiery Snake Spirit (H1 Rage Boost)"
EFFECT_NAME_SNAKES_FRENZY_BUFF = "Snake's Frenzy Reactive Boost"
EFFECT_NAME_CRIPPLING_STRIKE_CRIT = "Crippling Strike Command Crit"
EFFECT_NAME_FIREWING_ASHES_BURN_BOOST = "Firewing Ashes Burn Boost"
EFFECT_NAME_BONEGNAW_BUG_POISON_BOOST = "Bonegnaw Bug Poison Boost"
EFFECT_NAME_PAIN_N_FURY_RAGE_GAIN = "Pain N Fury Rage Gain"
EFFECT_NAME_ABYSSAL_MAW_BASIC_BOOST = "Abyssal Maw Basic Attack Buff"
EFFECT_NAME_ABYSSAL_MAW_COUNTER_BOOST = "Abyssal Maw Counterattack Buff"
EFFECT_NAME_BONE_SPURS_GENERAL_BOOST = "Bone Spurs General Damage Buff"
EFFECT_NAME_HARD_SHELL_DAMAGE_REDUCTION = "Hard Shell Damage Reduction"
EFFECT_NAME_UNTAMED_WILDERNESS_RAGE_GAIN = "Untamed Wilderness Rage Gain"
EFFECT_NAME_FLAME_SERPENT_BURN_BOOST = "Flame Serpent Burn Boost"
EFFECT_NAME_RAZOR_FANGS_POISON_BOOST = "Razor Fangs Poison Boost"
EFFECT_NAME_TEETH_N_CLAWS_GENERAL_BOOST = "Teeth N Claws General Damage Buff"
EFFECT_NAME_DRAGON_VENOMFIRE_BURN_BOOST = "Dragon Venomfire Burn Boost"
EFFECT_NAME_DRAGON_VENOMFIRE_POISON_BOOST = "Dragon Venomfire Poison Boost"
EFFECT_NAME_RAGEBEAST_SOUL_RAGE_GAIN = "Ragebeast Soul Rage Gain"
EFFECT_NAME_RETALIATION_FANGS_COUNTER_BOOST = "Retaliation Fangs Counterattack Buff"
EFFECT_NAME_INSPIRATION_ARRIVES_COUNTER_BOOST = "Inspiration Arrives Counter Boost"
EFFECT_NAME_SPIRITUAL_BLESSING_HEAL_BOOST = "Spiritual Blessing Heal Boost"
EFFECT_NAME_BEASTLY_RAGE_RAGE_GAIN = "Beastly Rage Rage Gain"
EFFECT_NAME_SHATTERBONE_BITE_GENERAL_BOOST = "Shatterbone Bite General Damage Buff"
EFFECT_NAME_IMPENETRABLE_SCALES_REDUCTION = "Impenetrable Scales Damage Reduction"
EFFECT_NAME_HEALING_LEAF_HEAL_BOOST = "Healing Leaf Heal Boost"
EFFECT_NAME_HOOF_STRIKE_COUNTER_BOOST = "Hoof Strike Counterattack Buff"
EFFECT_NAME_CORROSIVE_CLAWS_GENERAL_BOOST = "Corrosive Claws General Damage Buff"
EFFECT_NAME_PURPLE_GOLD_SCALES_REDUCTION = "Purple-Gold Scales Damage Reduction"
EFFECT_NAME_STINGING_TONGUE_DAMAGE = "Stinging Tongue Damage"
EFFECT_NAME_RAZOR_SHARP_SPIKES_BLEED_BOOST = "Razor Sharp Spikes Bleed Damage Boost"
EFFECT_NAME_SOUL_OF_FURY_RAGE_GAIN = "Soul of Fury Rage Gain"
EFFECT_NAME_BONE_SHATTER_JAW_BASIC_BOOST = "Bone-shatter Jaw Basic Attack Buff"
EFFECT_NAME_BLADED_SPINES_GENERAL_BOOST = "Bladed Spines General Damage Buff"
EFFECT_NAME_SCALE_ARMOR_SHIELD = "Scale Armor Shield"
EFFECT_NAME_STURDY_BONE_ARMOR_REDUCTION = "Sturdy Bone Armor Damage Reduction"
EFFECT_NAME_STRANGLED_DEATH_DAMAGE = "Strangled Death Damage"
EFFECT_NAME_BLOODY_JAWS_BLEED_BOOST = "Bloody Jaws Bleed Damage Boost"
EFFECT_NAME_BLOODTHIRST_GAZE_RAGE_GAIN = "Bloodthirst Gaze Rage Gain"
EFFECT_NAME_SEVERING_STRIKE_BASIC_BOOST = "Severing Strike Basic Attack Buff"
EFFECT_NAME_FROST_JOTUN_ROAR_GENERAL_BOOST = "Frost Jotun Roar General Damage Buff"
EFFECT_NAME_EMERALD_SCALES_REDUCTION = "Emerald Scales Damage Reduction"
EFFECT_NAME_FIREDRAKE_SOUL_BURN = "Firedrake Soul Burn"
EFFECT_NAME_FLAMING_CLAWS_BURN = "Flaming Claws Burn"
EFFECT_NAME_POISON_N_HEAL_POISON = "Poison N Heal Poison"
EFFECT_NAME_VENOM_RIP_POISON = "Venom Rip Poison"
EFFECT_NAME_VENOM_IMPACT_RAGE_GAIN = "Venom Impact Rage Gain"
EFFECT_NAME_BLAZING_WOLF_SPIRIT_RAGE_GAIN = "Blazing Wolf Spirit Rage Gain"
EFFECT_NAME_MOUNT_PERIODIC_RAGE_GAIN = "Mount Periodic Rage Gain"
EFFECT_NAME_MOUNT_REACTIVE_CRIT_BOOST = "Mount Reactive Crit Boost"
EFFECT_NAME_RAZOR_ARMOR_SHIELD = "Razor Armor Shield"
EFFECT_NAME_WINGED_GUARDIAN_SHIELD = "Winged Guardian Shield"
EFFECT_NAME_ARMOR_CHANT_REDUCTION = "Armor Chant Damage Reduction"
EFFECT_NAME_REPTILE_HEAL_REDUCTION = "Reptile Heal Damage Reduction"
EFFECT_NAME_SCALY_REBIRTH_REDUCTION = "Scaly Rebirth Damage Reduction"
EFFECT_NAME_BLOODTHIRSTY_EYE_RAGE_GAIN = "Bloodthirsty Eye Rage Gain"
EFFECT_NAME_MOUNT_COOP_CRIT_BOOST = "Mount Cooperation Crit Boost"
EFFECT_NAME_RIPPING_CLAWS_BLEED = "Ripping Claws Bleed"
EFFECT_NAME_DEER_REDEMPTION_CLEANSE = "Deer Redemption Cleanse"
EFFECT_NAME_SPIKED_SHIELD_SHIELD = "Spiked Shield Shield"
EFFECT_NAME_ICEDRAKE_BREATH_RAGE_GAIN = "Icedrake Breath Rage Gain"
EFFECT_NAME_FROSTWING_FURY_RAGE_GAIN = "Frostwing Fury Rage Gain"
EFFECT_NAME_FROSTWING_FURY_REDUCTION = "Frostwing Fury Damage Reduction"
EFFECT_NAME_KRAKEN_TOUCH_REDUCTION = "Kraken Touch Damage Reduction"
EFFECT_NAME_FATAL_CHOMP_BLEED = "Fatal Chomp Bleed"
EFFECT_NAME_FATAL_CHOMP_BASIC_BUFF = "Fatal Chomp Basic Attack Buff"
EFFECT_NAME_AGONIZING_FROST_BASIC_BUFF = "Agonizing Frost Basic Attack Buff"
EFFECT_NAME_DIVINE_AWE_CLEANSE = "Divine Awe Cleanse"
EFFECT_NAME_BLESSED_DEW_CLEANSE = "Blessed Dew Cleanse"
EFFECT_NAME_ICICLE_ARMOR_BLEED = "Icicle Armor Bleed"
EFFECT_NAME_ICICLE_ARMOR_SHIELD = "Icicle Armor Shield"
EFFECT_NAME_STEEL_SCALE_SHIELD = "Steel Scale Shield"
EFFECT_NAME_BLOODTHIRST_RECOVERY_BLEED = "Bloodthirst Recovery Bleed"

EFFECT_NAME_MASSIVE_SHIELD_BOOST = "Massive Shield Boost"
EFFECT_NAME_READY_TO_POUNCE_BUFF = "Ready to Pounce Buff"
EFFECT_NAME_PARALYZING_TERROR_SHIELD = "Paralyzing Terror Shield"
EFFECT_NAME_THREATENING_BLADE_DEF_BUFF = "Threatening Blade Defense Buff"

EFFECT_NAME_UNYIELDING_WILL_H2_RAGE_BOOST = "Unyielding Will (H2 Rage Boost)"
EFFECT_NAME_VIKING_SAGE_ATK_REDUCTION = "Viking Sage Attack Reduction"

# Plugin Skill Effect Names
EFFECT_NAME_PENDING_BLESSED_NEGATION_BUFF_REMOVAL = "PENDING_BLESSED_NEGATION_BUFF_REMOVAL"
EFFECT_NAME_PENDING_WILD_INDULGENCE_CLEANSE = "PENDING_WILD_INDULGENCE_CLEANSE"
EFFECT_NAME_BREAKING_FREE_DMG_BUFF = "Breaking Free Damage Buff"
EFFECT_NAME_BREAKING_FREE_COUNTER_REDUCTION = "Breaking Free Counter Reduction"
EFFECT_NAME_PENDING_BREAKING_FREE_CLEANSE = "PENDING_BREAKING_FREE_CLEANSE"
EFFECT_NAME_BLESSED_BY_FATE_BASIC_ATK_BUFF = "Blessed by Fate Basic Attack Buff"
EFFECT_NAME_BLESSED_BY_FATE_ENEMY_DMG_TAKEN_DEBUFF = "Blessed by Fate Enemy Damage Taken Debuff"

# --- New Plugin Skill Effect Names ---
EFFECT_NAME_FIERY_RAGE_BURN = "Fiery Rage Burn"
EFFECT_NAME_FIERY_DETONATION_DEF_REDUCTION = "Fiery Detonation Defense Reduction"
EFFECT_NAME_ENCHANTED_PURSUIT_BURN = "Enchanted Pursuit Burn"
EFFECT_NAME_ENCHANTED_PURSUIT_BLEED = "Enchanted Pursuit Bleed"
EFFECT_NAME_ON_ALERT_COUNTER_BUFF = "On Alert Counterattack Buff"
EFFECT_NAME_HELAS_CURSE_BURN = "Hela's Curse Burn"
EFFECT_NAME_HELAS_CURSE_DEF_REDUCTION = "Hela's Curse Defense Reduction"
EFFECT_NAME_FEARLESS_ATTACK_BUFF = "Fearless Attack Buff"

# --- Athelstan Skill Effect Names ---
EFFECT_NAME_ERUDITE_BURN_BOOST = "Erudite Burn Boost"
EFFECT_NAME_ERUDITE_POISON_BOOST = "Erudite Poison Boost"
EFFECT_NAME_STRATEGIZE_COMMAND_BUFF = "Strategize Command Buff"
EFFECT_NAME_ADAPTABLE_POISON = "Adaptable Poison"
EFFECT_NAME_HOLY_ENLIGHTENMENT_BURN = "Holy Enlightenment Burn"
EFFECT_NAME_HOLY_ENLIGHTENMENT_DMG_TAKEN_DEBUFF = "Holy Enlightenment Damage Taken Debuff"

# --- Verdandi Skill Effect Names ---
EFFECT_NAME_HUNTING_INSTINCT_BURN_BOOST = "Hunting Instinct Burn Boost"
EFFECT_NAME_HUNTING_EXPERIENCE_BURN = "Hunting Experience Burn"
EFFECT_NAME_RAINING_ARROWS_BURN = "Raining Arrows Burn"

# --- Olena Skill Effect Names ---
EFFECT_NAME_SCORCHING_ARROW_BURN_BOOST = "Scorching Arrow Burn Boost"
# Multi-Shot Arrow: Direct damage, no specific effect name needed for the damage itself.
# Poised Shot: Direct damage and direct rage reduction, no specific effect names needed.
EFFECT_NAME_ENCHANTED_ARROW_BURN = "Enchanted Arrow Burn"
EFFECT_NAME_CONCENTRATION_RAGE_GAIN = "Concentration Rage Gain Effect" # Custom effect for multi-round rage
EFFECT_NAME_VENGEFUL_FURY_BURN = "Vengeful Fury Burn"
EFFECT_NAME_SERRATED_FLOURISH_POISON = "Serrated Flourish Poison"

# --- Artur Skill Effect Names ---
EFFECT_NAME_TORMENT_BURN = "Torment Burn"
EFFECT_NAME_INCINERATION_BURN_BOOST = "Incineration Burn Damage Boost"
EFFECT_NAME_HELLFIRE_SHELTER_COUNTER_REDUCTION = "Hellfire Shelter Counter Damage Reduction"
EFFECT_NAME_SOUL_AWAKENING_COUNTER_REDUCTION = "Soul Awakening Counter Damage Reduction"

# --- Freydis Skill Effect Names ---
EFFECT_NAME_HEROIC_BLESSING_COUNTER_DEBUFF = "Heroic Blessing Counter Debuff"
EFFECT_NAME_PENDING_HEROIC_BLESSING_DEBUFF = "PENDING_HEROIC_BLESSING_DEBUFF"
EFFECT_NAME_PENDING_HEROIC_BLESSING_BUFF = "PENDING_HEROIC_BLESSING_BUFF"
EFFECT_NAME_HEROIC_BLESSING_BURN_BOOST = "Heroic Blessing Burn Boost"
EFFECT_NAME_BLADES_JUDGMENT_BURN = "Blade's Judgment Burn"
EFFECT_NAME_DESPERATE_STRIKE_BURN = "Desperate Strike Burn"
# --- Gregory Skill Effect Names ---
EFFECT_NAME_GREAT_MORALE_BUFF = "Great Morale Attack Buff"
EFFECT_NAME_DRUMMING_DISTURBANCE_HOT = "Drumming Disturbance Heal"
EFFECT_NAME_DRUMMING_DISTURBANCE_RAGE_REDUCTION = "Drumming Disturbance Rage Damage Reduction"
EFFECT_NAME_INSPIRING_DANCE_BASIC_BUFF = "Inspiring Dance Basic Attack Buff"

# --- Jens Skill Effect Names ---
EFFECT_NAME_GODLY_WRATH_COOP_RATE = "Godly Wrath Cooperation Boost"
EFFECT_NAME_DIVINE_ENERGIZE_VULNERABILITY = "Divine Energize Vulnerability"
EFFECT_NAME_HEAVENLY_DESCENT_BLEED = "Heavenly Descent Bleed"
EFFECT_NAME_DIVINE_PUNISHMENT_BASIC_BUFF = "Divine Punishment Attack Buff"
# --- Rollo Skill Effect Names ---
EFFECT_NAME_PATIENT_WAITING_BUFF = "Patient and Waiting Attack Buff"
EFFECT_NAME_TOUGH_CHOICE_BASIC_BUFF = "Tough Choice Basic Damage Buff"
EFFECT_NAME_TOUGH_CHOICE_COUNTER_DEBUFF = "Tough Choice Counter Damage Debuff"
EFFECT_NAME_BLOODY_PILLAGE_BLEED = "Bloody Pillage Bleed"
EFFECT_NAME_SEAS_GRACE_BLEED = "Sea's Grace Bleed"

# --- Harald Skill Effect Names ---
EFFECT_NAME_BATTLE_PREPARATION_BUFF = "Battle Preparation Attack Buff"
EFFECT_NAME_BATTLE_PREPARATION_DISARM_IMMUNITY = "Battle Preparation Disarm Immunity"
EFFECT_NAME_COORDINATED_STRIKE_BUFF = "Coordinated Strike Coop Damage Buff"
EFFECT_NAME_SLOW_STRIKE_BASIC_BUFF = "Slow Strike Basic Damage Buff"
EFFECT_NAME_FLEET_RAIDER_BUFF = "Fleet Raider Attack Buff"
EFFECT_NAME_RAGING_SMASH_SLOW = EFFECT_NAME_SLOW_DEBUFF

# --- Bjorn Skill Effect Names ---
EFFECT_NAME_FATAL_BLEEDING_DOT = "Fatal Bleeding DoT"
EFFECT_NAME_LETHAL_FRACTURE_ATK_BUFF = "Lethal Fracture Attack Buff"

# --- Hobert Skill Effect Names ---
EFFECT_NAME_BOLD_SHIELDAXE_BUFF = "Bold Shieldaxe Attack Buff"
EFFECT_NAME_STEADFAST_ARMOR_REDUCTION = "Steadfast Armor Damage Reduction"
EFFECT_NAME_BERSERK_FURY_BUFF = "Berserk Fury Basic Attack Buff"
EFFECT_NAME_BERSERK_FURY_RAGE_GAIN = "Berserk Fury Rage Gain"
EFFECT_NAME_DELAYED_RAGE_GAIN = "Delayed Rage Gain"
EFFECT_NAME_DELAYED_RAGE_REDUCTION = "Delayed Rage Reduction"
EFFECT_NAME_BRUTAL_BLOW_SHIELD = "Brutal Blow Shield"
EFFECT_NAME_PENDING_BRUTAL_BLOW_BUFF_REMOVAL = "PENDING_BRUTAL_BLOW_BUFF_REMOVAL"
EFFECT_NAME_PENDING_BRUTAL_BLOW_CLEANSE = "PENDING_BRUTAL_BLOW_CLEANSE"
EFFECT_NAME_PENDING_SEAS_GRACE_PURIFY = "PENDING_SEAS_GRACE_PURIFY"
EFFECT_NAME_PENDING_HEIMDALL_PURIFY = "PENDING_HEIMDALL_PURIFY"
EFFECT_NAME_PENDING_HEIMDALL_DISPEL = "PENDING_HEIMDALL_DISPEL"
EFFECT_NAME_HEIMDALL_STEALTH_EVASION = "Heimdall's Sapphire Evasion"
EFFECT_NAME_HEIMDALL_RETRIBUTION = "Heimdall's Sapphire Retribution"
EFFECT_NAME_HEIMDALL_DAMAGE_REDUCTION = "Heimdall's Sapphire Damage Reduction"
# --- Lagertha Skill Effect Names ---
EFFECT_NAME_SHIELDAXE_ATTACK_BLEED_BOOST = "Shieldaxe Attack Bleed Boost"
EFFECT_NAME_CHIEFS_MIGHT_BLEED = "Chief's Might Bleed"
EFFECT_NAME_SHIELD_BREAKER_BASIC_BUFF = "Shield Breaker Basic Attack Buff"
EFFECT_NAME_CUTTING_BLADE_BLEED_BOOST = "Cutting Blade Bleed Boost"
EFFECT_NAME_SHOWDOWN_BLEED = "Showdown Bleed"
EFFECT_NAME_SHOWDOWN_SHIELD = "Showdown Shield"
EFFECT_NAME_RIDE_THE_WAVES_PASSIVE = "Ride the Waves Basic Attack Buff"
EFFECT_NAME_RIDE_THE_WAVES_SURGE_BUFF = "Ride the Waves Surge Buff"
EFFECT_NAME_RAGING_TIDE_BLEED = "Raging Tide Bleed"
# --- Additional Plugin Effect Names ---
EFFECT_NAME_HALE_OF_THORNS_GENERAL_REDUCTION = "Hale of Thorns General Damage Debuff"
EFFECT_NAME_HALE_OF_THORNS_COUNTER_BUFF = "Hale of Thorns Counterattack Buff"
EFFECT_NAME_HALO_OF_SACRIFICE_BASIC_BUFF = "Halo of Sacrifice Basic Attack Buff"
EFFECT_NAME_PENDING_HALO_OF_SACRIFICE_CLEANSE = "PENDING_HALO_OF_SACRIFICE_CLEANSE"
EFFECT_NAME_HEIGHTENED_CHANCE_BASIC_BUFF = "Heightened Chance Basic Attack Buff"
EFFECT_NAME_HEIGHTENED_CHANCE_COUNTER_BUFF = "Heightened Chance Counterattack Buff"
EFFECT_NAME_RAPID_DEFENSE_BUFF = "Rapid Defense Buff"
EFFECT_NAME_RARE_VIKING_HYMN_ATTACK_BUFF = "Rare Viking Hymn Attack Buff"
EFFECT_NAME_RARE_DEFENSE_UP_BUFF = "Rare Defense Up Buff"
EFFECT_NAME_REST_AND_COUNTERATTACK_SHIELD = "Rest and Counterattack Shield"
EFFECT_NAME_SILENT_INVASION_BLEED = "Silent Invasion Bleed"
EFFECT_NAME_DEADLY_COUNTERATTACK_HEAL = "Deadly Counterattack Heal"
EFFECT_NAME_BONE_CORRODING_ARROW_REDUCTION = "Bone-corroding Arrow Damage Reduction"

# --- Helgar Skill Effect Names ---
EFFECT_NAME_SAINTLY_GUARDIAN_SHIELD_BOOST = "Saintly Guardian Shield Boost"
EFFECT_NAME_WAR_BLESSING_SHIELD = "War Blessing Shield"
EFFECT_NAME_JUDGEMENT_FURY_COUNTER_BUFF = "Judgement's Fury Counter Buff"
EFFECT_NAME_JUDGEMENT_MARKER = "Judgement Marker"
EFFECT_NAME_PENDING_JUDGEMENT_MARKERS = "PENDING_JUDGEMENT_MARKERS"

# --- Mount Skill Effect Names ---
EFFECT_NAME_PENDING_MOUNT_SHIELD_STRIP = "PENDING_MOUNT_SHIELD_STRIP"
EFFECT_NAME_RAVENS_BREATH_GENERAL_DAMAGE = "Raven's Breath General Damage"
EFFECT_NAME_DEER_BLESSING_DAMAGE_REDUCTION = "Deer Blessing Damage Reduction"
EFFECT_NAME_LAVA_BEAST_BURN = "Lava Beast Burn"
EFFECT_NAME_LAVA_BEAST_GENERAL_DAMAGE = "Lava Beast General Damage"
EFFECT_NAME_TOXIC_FLY_POISON = "Toxic Fly Poison"
EFFECT_NAME_TOXIC_FLY_GENERAL_DAMAGE = "Toxic Fly General Damage"
EFFECT_NAME_BLAZING_FIREBIRD_BURN = "Blazing Firebird Burn"
EFFECT_NAME_TOXIC_SPIKE_POISON = "Toxic Spike Poison"
EFFECT_NAME_CORROSIVE_POISON_REDUCTION = "Corrosive Poison Damage Reduction"

# --- Yulmi Skill Effect Names ---
EFFECT_NAME_DREADFUL_CURSE_POISON_BOOST = "Dreadful Curse Poison Boost"
EFFECT_NAME_HIGH_FIGHTING_SPIRIT_RAGE_BUFF = "High Fighting Spirit Rage Buff"
EFFECT_NAME_LOW_WHISPERS_REDUCTION = "Low Whispers Damage Reduction"
EFFECT_NAME_PLAGUE_POISON = "Plague Poison"
EFFECT_NAME_OPPORTUNE_STRIKE_POISON = "Opportune Strike Poison"
EFFECT_NAME_PLAGUE_DAMAGE_TAKEN_DEBUFF = "Plague Damage Taken Debuff"
EFFECT_NAME_UNDEAD_HARVEST_HP_REDUCTION = "Undead Harvest HP Reduction"

# --- Ivor Skill Effect Names ---
EFFECT_NAME_LAW_OF_VICTORY_RAGE_BUFF = "Law of Victory Rage Buff"
EFFECT_NAME_DEVASTATING_CHARGE_DEFENSE_BUFF = "Devastating Charge Defense Buff"
EFFECT_NAME_DEVASTATING_CHARGE_RALLY_BUFF = "Devastating Charge Rally Damage Buff"
EFFECT_NAME_SLAUGHTER_FEAST_ATTACK_BUFF = "Slaughter Feast Attack Buff"

# --- Rosky Skill Effect Names ---
EFFECT_NAME_BLADE_WIELDER_COUNTER_BOOST = "Blade Wielder Counter Boost"
EFFECT_NAME_MANIACAL_HOT = "Maniacal Heal"
EFFECT_NAME_PIRATE_TRICKS_SHIELD = "Pirate Tricks Shield"
EFFECT_NAME_FLURRY_REACTIVE_BOOST = "Flurry Reactive Damage Boost"
EFFECT_NAME_SPIRIT_BATTLESHIP_DEF_REDUCTION = "Spirit Battleship Defense Reduction"
EFFECT_NAME_POISON_ARROW_POISON = "Poison Arrow Poison"
EFFECT_NAME_POISON_ARROW_ATK_REDUCTION = "Poison Arrow Attack Reduction"
EFFECT_NAME_DIVINE_SHIELD_STRENGTH = "Divine Shield Shield Boost"
EFFECT_NAME_DIVINE_SHIELD_IMMUNITY = "Divine Shield Debuff Immunity"

# --- Alf Skill Effect Names ---
EFFECT_NAME_CHAIN_METEOR_BURN = "Chain Meteor Burn"
EFFECT_NAME_CHAIN_METEOR_POISON = "Chain Meteor Poison"
EFFECT_NAME_FIERY_POISON_BOMB_POISON = "Fiery Poison Bomb Poison"
EFFECT_NAME_AGILE_MISSILE_BURN = "Agile Missile Burn"
EFFECT_NAME_AGILE_MISSILE_EVASION = "Agile Missile Evasion"

# --- Sasha Skill Effect Names ---
EFFECT_NAME_NATURE_MARK = "Nature Mark"
EFFECT_NAME_NATURE_BLESSING_EVASION = "Nature Blessing Evasion"
EFFECT_NAME_FLORAL_BURIAL_POISON = "Floral Burial Poison"
EFFECT_NAME_NATURES_KILLER_POISON = "Nature's Killer Poison"
EFFECT_NAME_NATURES_KILLER_BURN = "Nature's Killer Burn"
EFFECT_NAME_BROKEN_BLADE_CHARGE_SHIELD = "Broken Blade Charge Shield"
EFFECT_NAME_TIME_OF_SEVERANCE_BLEED = "Time of Severance Bleed"
EFFECT_NAME_TIME_OF_SEVERANCE_RETRIBUTION = "Time of Severance Retribution"
EFFECT_NAME_SHATTERED_EDGE_BASIC_BUFF = "Shattered Edge Basic Attack Buff"
EFFECT_NAME_SHATTERED_EDGE_BLEED_BUFF = "Shattered Edge Bleed Damage Buff"
EFFECT_NAME_OATHBREAKERS_BLADE_REDUCTION = "Oathbreaker's Blade Damage Reduction"
EFFECT_NAME_EXILED_BLOODBLADE_BLEED = "Exiled Bloodblade Bleed"
EFFECT_NAME_EXILED_BLOODBLADE_SHIELD = "Exiled Bloodblade Shield"
EFFECT_NAME_WINTERS_CORONATION_BLEED = "Winter's Coronation Bleed"
EFFECT_NAME_WINTERS_CORONATION_SHIELD = "Winter's Coronation Shield"
EFFECT_NAME_WINTERS_CORONATION_PURIFY = "PENDING_WINTERS_CORONATION_PURIFY"
EFFECT_NAME_TRIUMPHANT_PRESENCE_RETRIBUTION = "Triumphant Presence Retribution"

# Marker effects should not be removed by cleanses/dispels.
PROTECTED_MARKER_EFFECTS = {
    EFFECT_NAME_JUDGEMENT_MARKER,
    EFFECT_NAME_PENDING_JUDGEMENT_MARKERS,
    EFFECT_NAME_NATURE_MARK,
}

EFFECT_NAME_NORTHERN_BLOOD_FEAST_BASIC_BUFF = "Northern Blood Feast Basic Attack Buff"
EFFECT_NAME_NORTHERN_BLOOD_FEAST_BLEED = "Northern Blood Feast Bleed"
EFFECT_NAME_COLD_IRON_OATH_DAMAGE = "Cold Iron Oath Damage"
EFFECT_NAME_ROYAL_AUTHORITY_RETRIBUTION = "Royal Authority Retribution"
EFFECT_NAME_ROYAL_AUTHORITY_DAMAGE_TAKEN = "Royal Authority Damage Taken Debuff"

# CUSTOM_SKILL_EFFECT processing priority (lower runs earlier).
CUSTOM_EFFECT_PRIORITY_DEFAULT = 50
CUSTOM_EFFECT_PRIORITY = {
    # Cleanses / purifies
    EFFECT_NAME_PENDING_AWAKENING_CLEANSE: 0,
    EFFECT_NAME_PENDING_WILD_INDULGENCE_CLEANSE: 0,
    EFFECT_NAME_PENDING_BREAKING_FREE_CLEANSE: 0,
    EFFECT_NAME_PENDING_BRUTAL_BLOW_CLEANSE: 0,
    EFFECT_NAME_PENDING_SEAS_GRACE_PURIFY: 0,
    EFFECT_NAME_PENDING_HEIMDALL_PURIFY: 0,
    EFFECT_NAME_PENDING_HALO_OF_SACRIFICE_CLEANSE: 0,
    EFFECT_NAME_DEER_REDEMPTION_CLEANSE: 0,
    EFFECT_NAME_DIVINE_AWE_CLEANSE: 0,
    EFFECT_NAME_BLESSED_DEW_CLEANSE: 0,
    EFFECT_NAME_WINTERS_CORONATION_PURIFY: 0,
    # Buff removals / dispels
    EFFECT_NAME_PENDING_LOKIS_TRICK_BUFF_REMOVAL: 1,
    EFFECT_NAME_PENDING_BLESSED_NEGATION_BUFF_REMOVAL: 1,
    EFFECT_NAME_PENDING_BRUTAL_BLOW_BUFF_REMOVAL: 1,
    EFFECT_NAME_PENDING_HEIMDALL_DISPEL: 1,
    EFFECT_NAME_PENDING_SHIELD_REFLECTOR_REMOVAL: 1,
    EFFECT_NAME_PENDING_MOUNT_SHIELD_STRIP: 1,
    # Marker conversions
    EFFECT_NAME_PENDING_JUDGEMENT_MARKERS: 2,
    # Rage reductions
    EFFECT_NAME_DELAYED_RAGE_REDUCTION: 3,
    # Rage gains
    EFFECT_NAME_FIRST_STRIKE_RAGE_AURA: 4,
    EFFECT_NAME_CONCENTRATION_RAGE_GAIN: 4,
    EFFECT_NAME_DELAYED_RAGE_GAIN: 4,
    EFFECT_NAME_BERSERK_FURY_RAGE_GAIN: 4,
    EFFECT_NAME_PAIN_N_FURY_RAGE_GAIN: 4,
    EFFECT_NAME_RAGEBEAST_SOUL_RAGE_GAIN: 4,
    EFFECT_NAME_UNTAMED_WILDERNESS_RAGE_GAIN: 4,
    EFFECT_NAME_MOUNT_PERIODIC_RAGE_GAIN: 4,
    EFFECT_NAME_BEASTLY_RAGE_RAGE_GAIN: 4,
    EFFECT_NAME_SOUL_OF_FURY_RAGE_GAIN: 4,
    EFFECT_NAME_BLOODTHIRST_GAZE_RAGE_GAIN: 4,
    EFFECT_NAME_VENOM_IMPACT_RAGE_GAIN: 4,
    EFFECT_NAME_BLAZING_WOLF_SPIRIT_RAGE_GAIN: 4,
    EFFECT_NAME_BLOODTHIRSTY_EYE_RAGE_GAIN: 4,
    EFFECT_NAME_ICEDRAKE_BREATH_RAGE_GAIN: 4,
    EFFECT_NAME_FROSTWING_FURY_RAGE_GAIN: 4,
    # Other custom buffs / evasion / retribution
    EFFECT_NAME_PENDING_HEROIC_BLESSING_DEBUFF: 5,
    EFFECT_NAME_PENDING_HEROIC_BLESSING_BUFF: 5,
    EFFECT_NAME_HEIMDALL_STEALTH_EVASION: 5,
    EFFECT_NAME_HEIMDALL_RETRIBUTION: 5,
    EFFECT_NAME_NATURE_BLESSING_EVASION: 5,
    EFFECT_NAME_AGILE_MISSILE_EVASION: 5,
    EFFECT_NAME_TIME_OF_SEVERANCE_RETRIBUTION: 5,
    EFFECT_NAME_TRIUMPHANT_PRESENCE_RETRIBUTION: 5,
    EFFECT_NAME_ROYAL_AUTHORITY_RETRIBUTION: 5,
}

# Custom effects that should not be skipped on their activation round.
CUSTOM_EFFECT_IMMEDIATE_EFFECTS = {
    EFFECT_NAME_FIRST_STRIKE_RAGE_AURA,
    EFFECT_NAME_PENDING_AWAKENING_CLEANSE,
    EFFECT_NAME_PENDING_LOKIS_TRICK_BUFF_REMOVAL,
    EFFECT_NAME_PENDING_BLESSED_NEGATION_BUFF_REMOVAL,
    EFFECT_NAME_PENDING_JUDGEMENT_MARKERS,
    EFFECT_NAME_PENDING_WILD_INDULGENCE_CLEANSE,
    EFFECT_NAME_PENDING_BREAKING_FREE_CLEANSE,
    EFFECT_NAME_CONCENTRATION_RAGE_GAIN,
    EFFECT_NAME_PENDING_BRUTAL_BLOW_BUFF_REMOVAL,
    EFFECT_NAME_PENDING_BRUTAL_BLOW_CLEANSE,
    EFFECT_NAME_PENDING_HEIMDALL_PURIFY,
    EFFECT_NAME_PENDING_HALO_OF_SACRIFICE_CLEANSE,
    EFFECT_NAME_PENDING_HEIMDALL_DISPEL,
    EFFECT_NAME_PENDING_SHIELD_REFLECTOR_REMOVAL,
    EFFECT_NAME_PENDING_MOUNT_SHIELD_STRIP,
    EFFECT_NAME_DEER_REDEMPTION_CLEANSE,
    EFFECT_NAME_DIVINE_AWE_CLEANSE,
    EFFECT_NAME_BLESSED_DEW_CLEANSE,
    EFFECT_NAME_WINTERS_CORONATION_PURIFY,
}
