"""
Contains all constant string literals for effect names, etc.
This helps avoid typos and makes it easier to manage these values.
"""

# --- Effect Name Constants ---
EFFECT_NAME_BROKEN_BLADE_DEBUFF = "BROKEN_BLADE_DEBUFF"
EFFECT_NAME_FIRST_STRIKE_RAGE_AURA = "FIRST_STRIKE_RAGE_AURA"
EFFECT_NAME_AWAKENING_DMG_REDUCTION = "Awakening Damage Reduction"
EFFECT_NAME_PENDING_AWAKENING_CLEANSE = "PENDING_AWAKENING_CLEANSE"
EFFECT_NAME_PENDING_LOKIS_TRICK_BUFF_REMOVAL = "PENDING_LOKIS_TRICK_BUFF_REMOVAL"
EFFECT_NAME_PENDING_SHIELD_REFLECTOR_REMOVAL = "PENDING_SHIELD_REFLECTOR_REMOVAL"
EFFECT_NAME_DISARM_DEBUFF = "Disarm Debuff"
EFFECT_NAME_SLOW_DEBUFF = "Slow Debuff"
EFFECT_NAME_SILENCE_DEBUFF = "Silence Debuff"


EFFECT_NAME_BLADE_COUNTER_BOOST = "Blade Counter Boost"
EFFECT_NAME_BLADE_COUNTER_IMMUNITY = "Broken Blade Immunity"
EFFECT_NAME_SHIELD_OF_RESISTANCE = "Shield of Resistance Effect"
EFFECT_NAME_REVENGE_ECHO_COUNTER_BOOST = "Revenge Echo Counter Boost"
EFFECT_NAME_HOLY_SHIELD_BOOST = "Holy Shield Boost"
EFFECT_NAME_DIVINE_RESISTANCE_BASIC_DMG_RED = "Divine Resistance (Basic Dmg Reduction)"
EFFECT_NAME_DIVINE_RESISTANCE_COUNTER_BOOST = "Divine Resistance (Counter Dmg Boost)"
EFFECT_NAME_HEALING_CHORDS_BOOST = "Healing Chords Boost"
EFFECT_NAME_HOLD_FAST_SHIELD = "Hold Fast Shield"
EFFECT_NAME_DETERMINED_DEFENSE_BROKEN_BLADE = EFFECT_NAME_BROKEN_BLADE_DEBUFF
EFFECT_NAME_TIT_FOR_TAT_DMG_RED = "Tit for Tat Damage Reduction"
EFFECT_NAME_SHARP_PURSUIT_SHIELD = "Sharp Pursuit Shield"
EFFECT_NAME_FLAME_GUARDIAN_SHIELD = "Flame Guardian Shield"
EFFECT_NAME_SACRED_BLADE_ATTACK_BOOST = "Sacred Blade Attack Boost"
EFFECT_NAME_SANCTITY_H2_RAGE_BOOST = "Sanctity of Life (H2 Rage Dmg Boost)"
EFFECT_NAME_VITAL_BLESSING_COUNTER_BOOST = "Vital Blessing Counter Boost"
EFFECT_NAME_VANQUISHING_BLADE_REDUCTION = "Vanquishing Blade Reduction"
EFFECT_NAME_DIVINE_BLESSING_REDUCTION = "Divine Blessing Reduction"
EFFECT_NAME_SHIELD_SUPPORT_EFFECT = "Shield Support Effect"
EFFECT_NAME_FREYAS_BLESSING_HEAL_BOOST = "Freya's Blessing Heal Boost"
EFFECT_NAME_HYMN_OF_LIFE_HOT = "Hymn of Life (HoT)"
EFFECT_NAME_HYMN_OF_LIFE_HP_BOOST = "Hymn of Life HP Boost"
EFFECT_NAME_SHIELD_REFLECTOR_BUFF = "Shield Reflector Buff"
EFFECT_NAME_BALDRS_SHIELD = "Baldr's Shield"
EFFECT_NAME_BALDRS_RESILIENCE = "Baldr's Resilience"
EFFECT_NAME_BALDRS_HEAL = "Baldr's Heal"
EFFECT_NAME_ODINS_ASYLUM_SHIELD = "Odin's Asylum Shield"
EFFECT_NAME_THORS_DETERMINATION_BUFF = "Thor's Determination Buff"
EFFECT_NAME_DISARMAMENT_DISARM = EFFECT_NAME_DISARM_DEBUFF
EFFECT_NAME_DISARMAMENT_SLOW = EFFECT_NAME_SLOW_DEBUFF

EFFECT_NAME_FIERY_SNAKE_SPIRIT_H1_BOOST = "Fiery Snake Spirit (H1 Rage Boost)"
EFFECT_NAME_SNAKES_FRENZY_BUFF = "Snake's Frenzy Reactive Boost"

EFFECT_NAME_MASSIVE_SHIELD_BOOST = "Massive Shield Boost"
EFFECT_NAME_READY_TO_POUNCE_BUFF = "Ready to Pounce Buff"
EFFECT_NAME_PARALYZING_TERROR_SHIELD = "Paralyzing Terror Shield"
EFFECT_NAME_THREATENING_BLADE_DEF_BUFF = "Threatening Blade Defense Buff"

EFFECT_NAME_UNYIELDING_WILL_H2_RAGE_BOOST = "Unyielding Will (H2 Rage Boost)"
EFFECT_NAME_VIKING_SAGE_ATK_REDUCTION = "Viking Sage Attack Reduction"

# Plugin Skill Effect Names
EFFECT_NAME_PENDING_BLESSED_NEGATION_BUFF_REMOVAL = "PENDING_BLESSED_NEGATION_BUFF_REMOVAL"
EFFECT_NAME_PENDING_WILD_INDULGENCE_CLEANSE = "PENDING_WILD_INDULGENCE_CLEANSE"
EFFECT_NAME_BREAKING_FREE_DMG_BUFF = "Breaking Free Damage Buff"
EFFECT_NAME_BREAKING_FREE_COUNTER_REDUCTION = "Breaking Free Counter Reduction"
EFFECT_NAME_PENDING_BREAKING_FREE_CLEANSE = "PENDING_BREAKING_FREE_CLEANSE"
EFFECT_NAME_BLESSED_BY_FATE_BASIC_ATK_BUFF = "Blessed by Fate Basic Attack Buff"
EFFECT_NAME_BLESSED_BY_FATE_ENEMY_DMG_TAKEN_DEBUFF = "Blessed by Fate Enemy Damage Taken Debuff"

# --- New Plugin Skill Effect Names ---
EFFECT_NAME_FIERY_RAGE_BURN = "Fiery Rage Burn"
EFFECT_NAME_FIERY_DETONATION_DEF_REDUCTION = "Fiery Detonation Defense Reduction"
EFFECT_NAME_ENCHANTED_PURSUIT_BURN = "Enchanted Pursuit Burn"
EFFECT_NAME_ENCHANTED_PURSUIT_BLEED = "Enchanted Pursuit Bleed"
EFFECT_NAME_ON_ALERT_COUNTER_BUFF = "On Alert Counterattack Buff"
EFFECT_NAME_HELAS_CURSE_BURN = "Hela's Curse Burn"
EFFECT_NAME_HELAS_CURSE_DEF_REDUCTION = "Hela's Curse Defense Reduction"
EFFECT_NAME_FEARLESS_ATTACK_BUFF = "Fearless Attack Buff"

# --- Athelstan Skill Effect Names ---
EFFECT_NAME_ERUDITE_BURN_BOOST = "Erudite Burn Boost"
EFFECT_NAME_ERUDITE_POISON_BOOST = "Erudite Poison Boost"
EFFECT_NAME_STRATEGIZE_COMMAND_BUFF = "Strategize Command Buff"
EFFECT_NAME_ADAPTABLE_POISON = "Adaptable Poison"
EFFECT_NAME_HOLY_ENLIGHTENMENT_BURN = "Holy Enlightenment Burn"
EFFECT_NAME_HOLY_ENLIGHTENMENT_DMG_TAKEN_DEBUFF = "Holy Enlightenment Damage Taken Debuff"

# --- Verdandi Skill Effect Names ---
EFFECT_NAME_HUNTING_INSTINCT_BURN_BOOST = "Hunting Instinct Burn Boost"
EFFECT_NAME_HUNTING_EXPERIENCE_BURN = "Hunting Experience Burn"
EFFECT_NAME_RAINING_ARROWS_BURN = "Raining Arrows Burn"

# --- Olena Skill Effect Names ---
EFFECT_NAME_SCORCHING_ARROW_BURN_BOOST = "Scorching Arrow Burn Boost"
# Multi-Shot Arrow: Direct damage, no specific effect name needed for the damage itself.
# Poised Shot: Direct damage and direct rage reduction, no specific effect names needed.
EFFECT_NAME_ENCHANTED_ARROW_BURN = "Enchanted Arrow Burn"
EFFECT_NAME_CONCENTRATION_RAGE_GAIN = "Concentration Rage Gain Effect" # Custom effect for multi-round rage

# --- Artur Skill Effect Names ---
EFFECT_NAME_TORMENT_BURN = "Torment Burn"
EFFECT_NAME_INCINERATION_BURN_BOOST = "Incineration Burn Damage Boost"
EFFECT_NAME_HELLFIRE_SHELTER_COUNTER_REDUCTION = "Hellfire Shelter Counter Damage Reduction"

# --- Freydis Skill Effect Names ---
EFFECT_NAME_HEROIC_BLESSING_COUNTER_DEBUFF = "Heroic Blessing Counter Debuff"
EFFECT_NAME_PENDING_HEROIC_BLESSING_DEBUFF = "PENDING_HEROIC_BLESSING_DEBUFF"
EFFECT_NAME_PENDING_HEROIC_BLESSING_BUFF = "PENDING_HEROIC_BLESSING_BUFF"
EFFECT_NAME_HEROIC_BLESSING_BURN_BOOST = "Heroic Blessing Burn Boost"
EFFECT_NAME_BLADES_JUDGMENT_BURN = "Blade's Judgment Burn"
EFFECT_NAME_DESPERATE_STRIKE_BURN = "Desperate Strike Burn"
# --- Gregory Skill Effect Names ---
EFFECT_NAME_GREAT_MORALE_BUFF = "Great Morale Attack Buff"
EFFECT_NAME_DRUMMING_DISTURBANCE_HOT = "Drumming Disturbance Heal"
EFFECT_NAME_DRUMMING_DISTURBANCE_RAGE_REDUCTION = "Drumming Disturbance Rage Damage Reduction"

# --- Jens Skill Effect Names ---
EFFECT_NAME_GODLY_WRATH_COOP_RATE = "Godly Wrath Cooperation Boost"
EFFECT_NAME_DIVINE_ENERGIZE_VULNERABILITY = "Divine Energize Vulnerability"
EFFECT_NAME_HEAVENLY_DESCENT_BLEED = "Heavenly Descent Bleed"
EFFECT_NAME_DIVINE_PUNISHMENT_BASIC_BUFF = "Divine Punishment Attack Buff"
# --- Rollo Skill Effect Names ---
EFFECT_NAME_PATIENT_WAITING_BUFF = "Patient and Waiting Attack Buff"
EFFECT_NAME_TOUGH_CHOICE_BASIC_BUFF = "Tough Choice Basic Damage Buff"
EFFECT_NAME_TOUGH_CHOICE_COUNTER_DEBUFF = "Tough Choice Counter Damage Debuff"
EFFECT_NAME_BLOODY_PILLAGE_BLEED = "Bloody Pillage Bleed"

# --- Harald Skill Effect Names ---
EFFECT_NAME_BATTLE_PREPARATION_BUFF = "Battle Preparation Attack Buff"
EFFECT_NAME_BATTLE_PREPARATION_DISARM_IMMUNITY = "Battle Preparation Disarm Immunity"
EFFECT_NAME_COORDINATED_STRIKE_BUFF = "Coordinated Strike Coop Damage Buff"
EFFECT_NAME_SLOW_STRIKE_BASIC_BUFF = "Slow Strike Basic Damage Buff"
EFFECT_NAME_FLEET_RAIDER_BUFF = "Fleet Raider Attack Buff"
EFFECT_NAME_RAGING_SMASH_SLOW = EFFECT_NAME_SLOW_DEBUFF

# --- Bjorn Skill Effect Names ---
EFFECT_NAME_FATAL_BLEEDING_DOT = "Fatal Bleeding DoT"
EFFECT_NAME_LETHAL_FRACTURE_ATK_BUFF = "Lethal Fracture Attack Buff"

# --- Hobert Skill Effect Names ---
EFFECT_NAME_BOLD_SHIELDAXE_BUFF = "Bold Shieldaxe Attack Buff"
EFFECT_NAME_STEADFAST_ARMOR_REDUCTION = "Steadfast Armor Damage Reduction"
EFFECT_NAME_BERSERK_FURY_BUFF = "Berserk Fury Basic Attack Buff"
EFFECT_NAME_BERSERK_FURY_RAGE_GAIN = "Berserk Fury Rage Gain"
EFFECT_NAME_DELAYED_RAGE_GAIN = "Delayed Rage Gain"
EFFECT_NAME_DELAYED_RAGE_REDUCTION = "Delayed Rage Reduction"
EFFECT_NAME_BRUTAL_BLOW_SHIELD = "Brutal Blow Shield"
EFFECT_NAME_PENDING_BRUTAL_BLOW_BUFF_REMOVAL = "PENDING_BRUTAL_BLOW_BUFF_REMOVAL"
EFFECT_NAME_PENDING_BRUTAL_BLOW_CLEANSE = "PENDING_BRUTAL_BLOW_CLEANSE"
# --- Additional Plugin Effect Names ---
EFFECT_NAME_HALE_OF_THORNS_GENERAL_REDUCTION = "Hale of Thorns General Damage Debuff"
EFFECT_NAME_HALE_OF_THORNS_COUNTER_BUFF = "Hale of Thorns Counterattack Buff"
EFFECT_NAME_HALO_OF_SACRIFICE_BASIC_BUFF = "Halo of Sacrifice Basic Attack Buff"
EFFECT_NAME_PENDING_HALO_OF_SACRIFICE_CLEANSE = "PENDING_HALO_OF_SACRIFICE_CLEANSE"
EFFECT_NAME_HEIGHTENED_CHANCE_BASIC_BUFF = "Heightened Chance Basic Attack Buff"
EFFECT_NAME_HEIGHTENED_CHANCE_COUNTER_BUFF = "Heightened Chance Counterattack Buff"
EFFECT_NAME_RAPID_DEFENSE_BUFF = "Rapid Defense Buff"
EFFECT_NAME_RARE_VIKING_HYMN_ATTACK_BUFF = "Rare Viking Hymn Attack Buff"
EFFECT_NAME_RARE_DEFENSE_UP_BUFF = "Rare Defense Up Buff"
